/*************************************************************************
	> File Name: init.c
	> Author: 
	> Mail: 
	> Created Time: 2018年09月10日 星期一 22时20分50秒
 ************************************************************************/
#include "init.h"

/* These symols are generated by ld (gcc linker). */
extern init_fn_t __initcall0_start;
extern init_fn_t __initcall1_start;
extern init_fn_t __initcall2_start;
extern init_fn_t __initcall3_start;
extern init_fn_t __initcall_end;
 
#define INIT_LEVEL_0 &__initcall0_start
#define INIT_LEVEL_1 &__initcall1_start
#define INIT_LEVEL_2 &__initcall2_start
#define INIT_LEVEL_3 &__initcall3_start
#define INIT_END     &__initcall_end


static init_fn_t * initcall_levels[] =
{
    INIT_LEVEL_0,
    INIT_LEVEL_1,
    INIT_LEVEL_2,
    INIT_LEVEL_3,
    INIT_END,
};

static void do_initcall_level(int level)
{
    init_fn_t *fn = NULL;
    
    for (fn = initcall_levels[level]; fn < initcall_levels[level + 1]; ++fn)
    {
        (*fn)();
    }
}

void do_initcalls(void)
{  
    int level = 0;  

    for (level = 0; level < ARRAY_SIZE(initcall_levels) - 1; level++)
    {
        do_initcall_level(level);
    }      
}


