/*************************************************************************
	> File Name: init.h
	> Author: 
	> Mail: 
	> Created Time: 2017年12月10日 星期日 15时47分30秒
 ************************************************************************/

#ifndef _INIT_H
#define _INIT_H

typedef void (*init_fn_t)(void);

#define DECLARE_INIT(func) \
        static init_fn_t __fn_##func \
        __attribute__((unused, section("init_sec"))) = func

/* These two symols are generated by ld (gcc linker). */
extern init_fn_t __start_init_sec;
extern init_fn_t __stop_init_sec;

#endif
