/*************************************************************************
	> File Name: init.c
	> Author: 
	> Mail: 
	> Created Time: 2018年09月10日 星期一 22时20分50秒
 ************************************************************************/
#include "init.h"

/* These two symols are generated by ld (gcc linker). */
extern init_fn_t __start_initcall0;
extern init_fn_t __start_initcall1;
extern init_fn_t __start_initcall2;
extern init_fn_t __start_initcall3;
extern init_fn_t __stop_initcall3;
 
#define INIT_LEVEL_0 &__start_initcall0
#define INIT_LEVEL_1 &__start_initcall1
#define INIT_LEVEL_2 &__start_initcall2
#define INIT_LEVEL_3 &__start_initcall3
#define INIT_END     &__stop_initcall3


static init_fn_t * initcall_levels[] =
{
    INIT_LEVEL_0,
    INIT_LEVEL_1,
    INIT_LEVEL_2,
    INIT_LEVEL_3,
    INIT_END,
};

static void __start(void){}
DECLARE_INIT0(__start);
DECLARE_INIT1(__start);
DECLARE_INIT2(__start);
DECLARE_INIT3(__start);

static void do_initcall_level(int level)
{
    init_fn_t *fn = NULL;
    
    for (fn = initcall_levels[level]; fn < initcall_levels[level + 1]; ++fn)
    {
        (*fn)();
    }
}

void do_initcalls(void)
{  
    int level = 0;  

    for (level = 0; level < ARRAY_SIZE(initcall_levels) - 1; level++)
    {
        do_initcall_level(level);
    }      
}


